/* --COPYRIGHT--,BSD
 * Copyright (c) 2017, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * --/COPYRIGHT--*/
/******************************************************************************
 * MSP432E4 Example project for ADC with multiple channel and single sequencer
 * with Timer Trigger
 *
 * Description: In this application example the ADC0 is configured for a single
 * sequencer sampling 4 channels in single ended mode. The ADC is triggered by
 * a timer running in periodic mode with a sampling frequency of 10 KHz. After
 * the conversion is completed an interrupt is generated by the ADC Sequencer
 * and the data is read by the CPU to be displayed on the serial console.
 *
 *                MSP432E401Y
 *             ------------------
 *         /|\|                  |
 *          | |                  |
 *          --|RST               |
 *            |               PE0|<-- AIN3
 *            |                  |
 *            |                  |
 *            |               PA0|<--U0RX
 *            |               PA1|-->U0TX
 * Author: Amit Ashara
*******************************************************************************/
/* DriverLib Includes */
#include <ti/devices/msp432e4/driverlib/driverlib.h>

/* Standard Includes */
#include <stdint.h>
#include <stdbool.h>

/* Display Include via console */
#include "uartstdio.h"
#include "arm_math.h"
#include "arm_const_structs.h"

#include "oled.h"



#define SYSTICK_FRAME_RATE 15
#define SYSTICK_SHOWTIME 3
#define SYSTICK_MAX_PAGE 2
#define SYSTICK_CLK_NUMSYS 60
bool setBufDisplayReady = false;
bool setClearDisplayReady = false;

int current_tick = 15;
int current_sec = 0 ;

int current_page = 0;

/* Global variables and defines for FFT */
#define NUM_SAMPLES 4096
#define SAMP_FREQ   16384
#define IFFTFLAG   0
#define BITREVERSE 1
volatile int16_t fftOutput[NUM_SAMPLES*2];

/* Global variables and defines for ADC */
static uint32_t dstBufferProcess[NUM_SAMPLES];
static uint32_t dstBufferNoneProcess[NUM_SAMPLES];
 bool setBufProcessReady = false;
int transferIndex = 0;

uint32_t getADCValue[1];
//volatile bool bgetConvStatus = false;;

/* Global variables and defines for dcRMS */
volatile float32_t rmsBuff;
volatile float32_t dcBuff;
float32_t rmsCalculation;



void ADC0SS2_IRQHandler(void)
{
    uint32_t getIntStatus;

    /* Get the interrupt status from the ADC */
    getIntStatus = MAP_ADCIntStatus(ADC0_BASE, 2, true);

    /* If the interrupt status for Sequencer-2 is set the
     * clear the status and read the data */
    if(getIntStatus == 0x4)
    {
        /* Clear the ADC interrupt flag. */
        MAP_ADCIntClear(ADC0_BASE, 2);

        /* Read ADC Value. */
        MAP_ADCSequenceDataGet(ADC0_BASE, 2, getADCValue);

        /* Self Jugle Part Start*/
        if(setBufProcessReady == false)
        {
            if(transferIndex<NUM_SAMPLES)
            {
                dstBufferNoneProcess[transferIndex] = getADCValue[0] ;
                dstBufferProcess[transferIndex] = getADCValue[0]*7 ;

                transferIndex ++ ;
            }
            else
            {

                setBufProcessReady = true ;
                transferIndex = 0 ;
            }
            
        }
        /* Self Jugle Part End*/

        //bgetConvStatus = true;
    }
}

void ConfigureUART(uint32_t systemClock)
{
    /* Enable the clock to GPIO port A and UART 0 */
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);

    /* Configure the GPIO Port A for UART 0 */
    MAP_GPIOPinConfigure(GPIO_PA0_U0RX);
    MAP_GPIOPinConfigure(GPIO_PA1_U0TX);
    MAP_GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);

    /* Configure the UART for 115200 bps 8-N-1 format */
    UARTStdioConfig(0, 115200, systemClock);
}

int main(void)
{
    uint32_t systemClock;

    //uint32_t setFFTmaxValue;
    //uint32_t setFFTmaxFreqIndex;
    //int_fast32_t i32IPart[3];
    //int_fast32_t i32FPart[3];
    
    /* Configure the system clock for 120 MHz */
    systemClock = MAP_SysCtlClockFreqSet((SYSCTL_XTAL_25MHZ | SYSCTL_OSC_MAIN |
                                          SYSCTL_USE_PLL | SYSCTL_CFG_VCO_480),
                                          120000000);

    /* Initialize serial console */
    ConfigureUART(systemClock);

    OLED_Init(); 
    OLED_Clear();

    /* Enable the clock to GPIO Port E and wait for it to be ready */
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOE);
    while(!(MAP_SysCtlPeripheralReady(SYSCTL_PERIPH_GPIOE)))
    {
    }

    /* Configure PE0-PE3 as ADC input channel */
    MAP_GPIOPinTypeADC(GPIO_PORTE_BASE, GPIO_PIN_1);
 
    /* Enable the clock to ADC-0 and wait for it to be ready */
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_ADC0);
    while(!(MAP_SysCtlPeripheralReady(SYSCTL_PERIPH_ADC0)))
    {
    }

    MAP_ADCSequenceStepConfigure(ADC0_BASE, 2, 0, ADC_CTL_CH2 | ADC_CTL_IE |
                                 ADC_CTL_END);

    /* Enable sample sequence 2 with a timer signal trigger.  Sequencer 2
     * will do a single sample when the timer generates a trigger on timeout*/
    MAP_ADCSequenceConfigure(ADC0_BASE, 2, ADC_TRIGGER_TIMER, 2);

    /* Since sample sequence 2 is now configured, it must be enabled. */
    MAP_ADCSequenceEnable(ADC0_BASE, 2);

    /* Clear the interrupt status flag before enabling. This is done to make
     * sure the interrupt flag is cleared before we sample. */
    MAP_ADCIntClear(ADC0_BASE, 2);
    MAP_ADCIntEnable(ADC0_BASE, 2);

    /* Enable the Interrupt generation from the ADC-0 Sequencer */
    MAP_IntEnable(INT_ADC0SS2);

    /* Enable Timer-0 clock and configure the timer in periodic mode with
     * a frequency of 10 KHz. Enable the ADC trigger generation from the
     * timer-0. */
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
    while(!(MAP_SysCtlPeripheralReady(SYSCTL_PERIPH_TIMER0)))
    {
    }

    MAP_TimerConfigure(TIMER0_BASE, TIMER_CFG_A_PERIODIC);
    MAP_TimerLoadSet(TIMER0_BASE, TIMER_A, (systemClock/SAMP_FREQ));
    MAP_TimerADCEventSet(TIMER0_BASE, TIMER_ADC_TIMEOUT_A);
    MAP_TimerControlTrigger(TIMER0_BASE, TIMER_A, true);
    MAP_TimerEnable(TIMER0_BASE, TIMER_A);


    //Var Part Start

    //Var Part End
    while(1)
    {

        if(setBufProcessReady == true)
        {
            int16_t Effect_FFTIndex[10] = {0}; 

            arm_cfft_q15(&arm_cfft_sR_q15_len4096, (q15_t *)dstBufferProcess, IFFTFLAG,
                         BITREVERSE);
            arm_cmplx_mag_q15((q15_t *)dstBufferProcess, (q15_t *)fftOutput,
                              NUM_SAMPLES);
            //arm_max_q15((q15_t *)fftOutput, NUM_SAMPLES, (q15_t *)&setFFTmaxValue,
            //            &setFFTmaxFreqIndex);

            //i32IPart[2] = (int32_t)((setFFTmaxFreqIndex * SAMP_FREQ) / NUM_SAMPLES);
            //i32FPart[2] = (int32_t)(((setFFTmaxFreqIndex * SAMP_FREQ) / NUM_SAMPLES) * 1000);
            //i32FPart[2] = i32FPart[2] - i32IPart[2] * 1000;

            //for(int index = 1 ; index < NUM_SAMPLES ; index++)
            //{
            //    UARTprintf("any:%3d,%3d\n", ((int16_t*)fftOutput)[index],index);
            //    //UARTprintf("any:%0d,%3d\n", ((uint32_t*)dstBufferNoneProcess)[index],index);
            //}

            
            //Find Effect Index
            int Effect_FFTNum = 0;
            for(int temp_index = 1;temp_index<NUM_SAMPLES/3;temp_index++)
            {
                
                if(fftOutput[temp_index]>0)
                {
                    Effect_FFTIndex[Effect_FFTNum] = temp_index ;
                    Effect_FFTNum ++ ;
                }
            }
            
            //Calc THD All
            float32_t THDBuf = (float32_t)0.0;
            float32_t THD = (float32_t)0.0;
            for(int temp_index = 1;temp_index<Effect_FFTNum;temp_index++)
            {
                THDBuf += (float32_t)fftOutput[Effect_FFTIndex[temp_index]] * (float32_t)fftOutput[Effect_FFTIndex[temp_index]] ;
            }
            arm_sqrt_f32(THDBuf, &THD);
            THD = THD/ (float32_t)fftOutput[Effect_FFTIndex[0]]  ;

            
            
            //Calc Base Harmonic Freq
            float32_t BasicFreq  = 0;
            //uint32_t  BasicAmp  = 0;
            BasicFreq =  (float32_t)Effect_FFTIndex[0]* (float32_t)SAMP_FREQ / (float32_t)NUM_SAMPLES ;
            float32_t Jmp_Step =  (BasicFreq * (float32_t)128) / (float32_t)2 * (float32_t)SAMP_FREQ ;
            //BasicAmp  =  fftOutput[Effect_FFTIndex[0]] ;

            //Calc 1st Harmonic Normalize
            float32_t Normal_1stAmp = (float32_t)fftOutput[Effect_FFTIndex[1]] / (float32_t)fftOutput[Effect_FFTIndex[0]] ;

            //Calc 3rd Harmonic Normalize
            uint32_t Normal_2ndAmp = (float32_t)fftOutput[Effect_FFTIndex[3]] / (float32_t)fftOutput[Effect_FFTIndex[0]];


            
            OLED_Clear();
            delay_ms(1000) ;
            OLED_Value_One_Page(THD,BasicFreq,Normal_1stAmp,Normal_2ndAmp) ;
            //OLED_Wave_showing(dstBufferNoneProcess,1);
            delay_ms(2000) ;

 
            /*
            //int32_t Test = (int32_t)(THD *1000) ;
            //int32_t BasicFreqTest =  (int32_t)(BasicFreq *1000) ;
            for(int index = 1 ; index < NUM_SAMPLES ; index++)
            {
                //UARTprintf("any:%3d,%3d\n", BasicFreqTest,Test);
                //UARTprintf("any:%3d,%3d\n", ((int16_t*)fftOutput)[index],index);
                //UARTprintf("any:%3d,%3d,%3d\n", ((int16_t*)fftOutput)[index],index,Test);
                //UARTprintf("any:%0d,%3d\n", ((uint32_t*)dstBufferNoneProcess)[index],index);
            }*/

            setBufProcessReady = false ;
        }

    }
}
